# The list of vouched (or actively denounced) users for this repository.
#
# The high-level idea is that only vouched users can participate in
# contributing to this project. And a denounced user is explicitly
# blocked from contributing (issues, PRs, etc. auto-closed).
#
# We choose to maintain a denouncement list rather than or in addition to
# using the platform's block features so other projects can slurp in our
# list of denounced users if they trust us and want to adopt our prior
# knowledge about bad actors.
#
# Syntax:
#  - One handle per line (without @). Sorted alphabetically.
#  - Optionally specify platform: `platform:username` (e.g., `github:mitchellh`).
#  - To denounce a user, prefix with minus: `-username` or `-platform:username`.
#  - Optionally, add details after a space following the handle.
#
# Maintainers can vouch for new contributors by commenting "lgtm" on an
# issue by the author. Maintainers can denounce users by commenting
# "denounce" or "denounce [username]" on an issue or PR.
12089897411
adamgreig
anhosh
avarel
awestlake87
bryceberger
burtonageo
crumblingstatue
devxpain
dolezvo1
emilk
-enomado
eupraxia05
feriixu
fricze
gui-yom
hydra
itsethra
jakobhellermann
jengamon
jerrody
knoellle
lain-dono
lennyslounge
lukep0wers
lvaroqui
matiaslopezing
mcthesw
micfong-z
mkeeter
morphexe
msheldyakov
parkertenbroeck
past9
paul-hansen
ptxmac
quinntyx
regenjacob
sof3
tautropfli
toppdev
ved-s
vickerinox
white-axe
zkldi
